### ISSUE TITLE
Make slider values be changable by keyboard input

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamber#12]
Let's take the 2-Point Function for example.
If I were to select an initial SV of exactly 1.39, it would be very hard or even impossible to select that value with the slider, because of the size of it. Another problem is that, when moving the slider, you cannot get all values, because the slider is set to skip a lot of numbers. Same goes for the other values in the 2-Point Function and the sliders in the Stutter Function as well, although the sliders there are large enough to pinpoint an exact value.

My suggestion would be to be able to change the value manually with keyboard input, by creating an editable text box when clicking on the value itself or even making the value itself a text box, like the "Intermediate Points" value, like you had in your alpha release. 

Example is provided in the image.
![amber_2018-07-07_11-40-15](https://user-images.githubusercontent.com/22303902/42409446-e0a20e28-81da-11e8-8e30-2fac45254227.png)

**Comment by Eve-ning** [comment]
With beta you can use the keyboard inputs to nudge it by 0.01 while hovering the slider, that's not very intuitive but that's a workaround for now. Will see if I can make this better some time in the future

**Comment by Eve-ning** [comment]
To add onto this, I had an issue where you can't have certain values since the 2 widgets (slider and box) have to interact with each other. This will be the temporary solution unless I find a solution

**Comment by longnguyen2004** [comment]
Maybe update one when the other is changed? You're using Qt, just utilize the signals and slots mechanism. Here's my approach:

1. Enable slider tracking (so that the spin box is updated in real time while you're dragging the slider)
2. Make 2 functions, one for updating the spin box, the other for updating the slider bar (you can use lambdas for this)
3. When one changes, block the signals for the other one (so that they don't get stuck in an infinite loop), change the value, then unblock the signals.

I'll probably make a PR for this.

**Comment by Eve-ning** [comment]
yea I wasn't sure how to block a signal while one is active since I didn't read too much into signals and slots, the problem was the infinite loop as you mentioned, I'll look into it if I ever come back to this, thanks!

also for the PR, I think I'll come back to this soon (early next year) so I'll probably reorganize everything, Please don't pressure yourself in finding the solution, this code is really old, so I feel like any solution will end up being temporary, I'll make it more flexible/readable

**Comment by longnguyen2004** [comment]
Actually I've already come up with a solution, but I'll have to wait until early next year xD

I'm planning to make a function that will effectively "bind" a spinbox to a slider, so that you can just call BindValue(spinbox, slider) once, and then they'll update eachother's value automatically. Further more, since Qt has provided abstracts for the spinbox (QAbstractSpinbox) and slider (QAbstractSlider), I can adapt my code to work with any type of spinbox and slider.

**Comment by Eve-ning** [comment]
in the meantime i'll restructure everything, I'll consider your idea once I'm done with most of it

**Comment by longnguyen2004** [comment]
ok i'll wait

**Comment by Eve-ning** [comment]
I've started to just rework the basic structure of parsing these maps, I'm expecting to finish reworking on amber by around early Jan

**Comment by longnguyen2004** [comment]
Alright just take your time.
Btw can you put the new code up into a separate branch?

**Comment by Eve-ning** [comment]
sure, im working on https://github.com/Eve-ning/amber_base, it's an entirely separate project that amber will depend on.
amber currently has the issue where i can't dynamically link it, so the current amber_base is hardcoded into it lol

**Comment by longnguyen2004** [comment]
haha :D in these cases you should use Visual Studio, it's easier that way, then use Qt Creator for everything else
also this might be helpful: https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2017

**Comment by Eve-ning** [comment]
mm yea it's a good idea to switch to VS to link these things, i'll see how it goes down the road and see if I can make Qt behave. Thanks for the article

**Comment by longnguyen2004** [comment]
just a note here, i saw you using function/operator overloading in your code, so do NOT add `extern "C"` into it, or else you'll have a lot of trouble later on
this guide is a bit better: http://programmingexamples.wikidot.com/blog:1

**Comment by Eve-ning** [comment]
yea i have no idea what's an extern "C" so that's good i guess

**Comment by Eve-ning** [comment]
Don't think I'll address this issue specifically, it's possible to adjust slider values via keyboard input by making the sliders active and pressing **Left/Right Arrow**

I'll possibly come back to implementing **DoubleSpinBox** and **Slider** connect, but it's a bit of a hassle to organize those
