### ISSUE TITLE
Suggestion for future rewrite of code

### ISSUE THREAD

**Issue by longnguyen2004** [Eve-ning/reamber#15]
Just a suggestion if you plan to revisit this code in the future: 
Split each tool in the program to its own .cpp and .h file.

Putting everything into a single .cpp file like this makes it very hard to fix bugs. Splitting the code into multiple files makes it easier for you to implement new features, and also for others to fix bugs in the program.

You can take a look at my tool [here](https://github.com/longnguyen2004/osuSVTool), to get an idea of what I'm talking about.

I'm writing this mainly because I can actually fix most of the current issues, but looking at your code just makes me give up (not because it's bad tho, it's just not organized)

**Comment by Eve-ning** [comment]
understandable, it's my first bigger projects on Qt, so it gets really disorganized really fast with a lot of band-aid solution fixing

I'll see if I can reorganize everything in the future, probably early next year

**Comment by longnguyen2004** [comment]
Your current solution will probably get disorganized again pretty fast, seeing that you dumped everything into mainwindow.cpp. Like I said, treat each tool as its own widget that inherits off of QWidget (or QDialog). Then, when the user choose a tool, hide the main window and show the subwindow. For the main window to show up again after the user closes, just connect a function to the close() signal of the subwindow.

For better clarity, your files would go something like this.

mainwindow.cpp
```
// constructor/destructor stuff
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    connect(this->ui.Copier, &QPushButton::pressed, [this]() {
        this->hide();
        Copier *w = new Copier()           // this is to prevent the widget to destruct itself when out of scope
        w->setAttribute(Qt::WA_DeleteOnClose);
        connect(Copier, SIGNAL(destroyed()), this, SLOT(show()));
    });
    // implement the rest of the tool yourself
}

MainWindow::~MainWindow()
{
    delete ui;
}
```
This way, the main window will hide and show automatically

**Comment by Eve-ning** [comment]
I kind of misunderstood what you meant by grouping these things together, I tried to enforce it in the reamber_base library but not this yet. I went straight for the Qt Designer way of creating the ui so everything is just dropped in the mainwindow.

I don't really like separating each tool to its own window, I prefer if it's all in one since alt-tabbing around windows gets really confusing for me. I'll see if I can group functions together and put them in classes inherited by MainWindow somehow, but for now I'm adamant on having a single window

**Comment by longnguyen2004** [comment]
Well you can also call the QWidget constructor with "this" as the parent, that way the new widget will be drawn ON TOP of the previous one (so you'll need to hide that somehow)

I'll spend a couple hours tomorrow trying to implement this, that way you'll have a better view of what I mean

**Comment by Eve-ning** [comment]
ehh I think I'll just go with the QStackedWidget, it's neater, I'll do:
```
mainwindow.h
mainwindow.cpp
mainwindow_copier.cpp
mainwindow_normalizer.cpp
...
```

> 
> 
> Well you can also call the QWidget constructor with "this" as the parent, that way the new widget will be drawn ON TOP of the previous one (so you'll need to hide that somehow)
> 
> I'll spend a couple hours tomorrow trying to implement this, that way you'll have a better view of what I mean

sorry I really don't want to have multiple windows, it just seems more confusing for me to reference multiple uis, the current one I have is working fine for me

**Comment by longnguyen2004** [comment]
Yeah you can do that as well. Also it's helpful to create folders for each of them, because they'll have .h files to go along with them (or not if you go this route)

**Comment by Eve-ning** [comment]
# Qt mainwindow.cpp & .h cluttering

## Current Solution
What I'll do for now is to format ```mainwindow.h``` as clearly as possible, it'll aid a lot in finding functions in the header. Whereas for ```mainwindow.cpp``` I'll just make sure it's sorted as depicted in the header. 

I'm not too concerned about how clean the .cpp is since navigating from .h using **Switch Header/Source** is easy enough.

## Rejected Ideas
I think I'll just leave this formatting as it is, here are the reasons:
**Using multiple .cpps**
```
mainwindow.h
mainwindow.cpp
mainwindow_copier.cpp
mainwindow_normalizer.cpp
```
I ran into multiple ```#include``` issues, and I found that most of these are a bit redundant. I found that just looking for the functions themselves (Qt has automatically formatted these nicely), and switching Header/Source is easy enough.

**Multiple Windows**
I tried to visualize what amber would look like with multiple window UI, unfortunately due to how osu! is already a window, usually full screen, it'll be very annoying to find the correct UI by flipping back and forth windows. While I think this will be beneficial on organization of code, it loses out on user-friendliness

## Possible Future Implementations
What I think can work in cleaning up the code is to move all "complicated calculations" (eg. curve calculations in TPF) into a separate namespace class, this may be a bit redundant since it's not **very complex** but we'll see in the future.

If there are clutter issues in the future I'll refer back to this, but for now I'll close

**Comment by longnguyen2004** [comment]
Alright, just hope that you already have a clear picture of what you're doing.

For now, I'll fork this repo and do all my rewrite there. If the code happens to get disorganized again, at least you'll have a reference of what I'm trying to do.
